name: doc2vec
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.11
  - pip
  - numpy
  - pandas=2.1.1
  - scikit-learn=1.3.0
  - scipy=1.11.3
  - faiss-gpu=1.8.0
  - cudatoolkit=11.8
  - pytorch=2.0.1
  - torchvision
  - torchaudio
  - tqdm=4.66.1
  - pillow=10.0.1
  - protobuf=4.24.4
  - python-dateutil=2.8.2
  - pytz=2023.3
  - pyyaml=6.0.1
  - typing-extensions=4.7.1
  - pip:
      - mecab-python3==1.0.5
      - tiktoken==0.7.0
      - tokenizers==0.13.3
      - transformers==4.31.0
      - regex>=2020.11.13,<2024.0.0
      - certifi==2023.7.22
      - charset-normalizer==3.3.0
      - elastic-transport==8.4.0
      - elasticsearch==8.4.0
      - filelock==3.12.2
      - fsspec==2023.9.1
      - gensim==4.3.1
      - huggingface-hub==0.17.3
      - idna==3.4
      - jinja2==3.1.2
      - joblib==1.3.2
      - jpype1==1.5.0
      - konlpy==0.6.0
      - lxml==4.9.3
      - markupsafe==2.1.3
      - mpmath==1.3.0
      - networkx==3.1
      - python-dotenv==1.0.0
      - requests==2.31.0
      - safetensors==0.3.3
      - six==1.16.0
      - smart-open==6.3.0
      - sympy==1.12
      - threadpoolctl==3.2.0
      - wrapt==1.14.1
      - uvicorn==0.18.3
